#!/usr/bin/perl -w
$|++; ##  Disable output buffering
$time=0;
while(<>)
{ 
   $th=`date +%H`;
   $tm=`date +%M`;
   $x=$th*60+$tm;
   $time=$x/60;
   if ( !((m/swap/) || (m/memory/) || (m/State/) || (m/device/) || (m/CPU/)) )
         { printf("%d %d %3.2f  %s", $th,$tm,$time,$_); }

}
